"""
ACL Configuration Generator
Manages IP whitelist for SIP registration
"""
import json
import logging
import subprocess
from typing import List

from database import get_db, SystemSettings

logger = logging.getLogger(__name__)

ACL_CONFIG_PATH = "/etc/asterisk/custom/acl.conf"


def generate_acl_config(ips: List[str]) -> str:
    """Generate Asterisk acl.conf content with whitelist."""
    config = """; Auto-generated ACL configuration
; Generated by GonoPBX

[registration-whitelist]
deny=0.0.0.0/0.0.0.0
"""
    for ip in ips:
        config += f"permit={ip}\n"

    return config


def write_acl_config(ips: List[str]) -> bool:
    """Write acl.conf to the shared config directory."""
    try:
        import os
        os.makedirs(os.path.dirname(ACL_CONFIG_PATH), exist_ok=True)

        with open(ACL_CONFIG_PATH, 'w') as f:
            f.write(generate_acl_config(ips))

        logger.info(f"ACL config written with {len(ips)} permitted IPs")
        return True
    except Exception as e:
        logger.error(f"Failed to write ACL config: {e}")
        return False


def remove_acl_config() -> bool:
    """Remove acl.conf when whitelist is disabled."""
    try:
        import os
        if os.path.exists(ACL_CONFIG_PATH):
            # Write empty config (no deny/permit = allow all)
            with open(ACL_CONFIG_PATH, 'w') as f:
                f.write("; ACL disabled\n")
        logger.info("ACL config cleared (whitelist disabled)")
        return True
    except Exception as e:
        logger.error(f"Failed to remove ACL config: {e}")
        return False


def reload_acl() -> bool:
    """Reload ACL module in Asterisk container."""
    try:
        result = subprocess.run(
            ['docker', 'exec', 'pbx_asterisk', 'sh', '-c',
             'cp /etc/asterisk/custom/acl.conf /etc/asterisk/acl.conf 2>/dev/null; asterisk -rx "module reload res_acl"'],
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            logger.info("Asterisk ACL reloaded successfully")
            return True
        else:
            logger.error(f"ACL reload failed: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Failed to reload ACL: {e}")
        return False


def get_whitelist_settings() -> dict:
    """Read whitelist settings from database."""
    db = next(get_db())
    try:
        enabled_setting = db.query(SystemSettings).filter(
            SystemSettings.key == "ip_whitelist_enabled"
        ).first()
        ips_setting = db.query(SystemSettings).filter(
            SystemSettings.key == "ip_whitelist"
        ).first()

        enabled = enabled_setting.value == "true" if enabled_setting else False
        ips = json.loads(ips_setting.value) if ips_setting and ips_setting.value else []

        return {"enabled": enabled, "ips": ips}
    finally:
        db.close()
